// <auto-generated />
using System;
using BetStats.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetStats.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BetStatsDbContext))]
    [Migration("20261008171605_FootballResultsOutcomeProvenance")]
    partial class FootballResultsOutcomeProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingestion")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetStats.Domain.Coverage.CoverageEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Basis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RawId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<Guid[]>("SupportingObservationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RawId", "SourceId");

                    b.HasIndex("SourceId", "RecordedAtUtc", "Id");

                    b.ToTable("Evidence", "coverage", t =>
                        {
                            t.HasCheckConstraint("CK_CoverageEvidence_Claim", "\"Claim\" IN ('Unknown','Partial','VerifiedComplete','VerifiedEmpty') AND \"Basis\" IN ('ManualStatement','OwnedFixtureInventory')");

                            t.HasCheckConstraint("CK_CoverageEvidence_Hash", "\"RawHash\" ~ '^[0-9a-f]{64}$' AND length(btrim(\"EvidenceReference\")) > 0 AND cardinality(\"SupportingObservationIds\") <= 1000");

                            t.HasCheckConstraint("CK_CoverageEvidence_Version", "\"Version\" > 0 AND \"AvailableAtUtc\" >= \"RetrievedAtUtc\" AND \"AvailableAtUtc\" <= \"RecordedAtUtc\" AND \"ValidUntilUtc\" > \"AvailableAtUtc\"");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Coverage.CoverageReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BasisReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EvidenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceId", "Sequence")
                        .IsUnique();

                    b.ToTable("Reviews", "coverage", t =>
                        {
                            t.HasCheckConstraint("CK_CoverageReview_State", "\"Sequence\" > 0 AND \"Status\" IN ('Approved','Rejected') AND \"ReviewedAtUtc\" <= \"RecordedAtUtc\" AND length(btrim(\"BasisReference\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Coverage.EventTimeEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CorrectsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DateObservationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RawId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorrectsId")
                        .IsUnique();

                    b.HasIndex("DateObservationId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RawId", "SourceId");

                    b.HasIndex("ProviderIdentityId", "RecordedAtUtc", "Id");

                    b.ToTable("EventTimes", "coverage", t =>
                        {
                            t.HasCheckConstraint("CK_EventTime_Version", "\"Version\" > 0 AND \"AvailableAtUtc\" >= \"RetrievedAtUtc\" AND \"AvailableAtUtc\" <= \"RecordedAtUtc\" AND \"RawHash\" ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Football.FootballResultObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AwayId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("CorrectsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DateObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RawId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceEventReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwayId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CorrectsId")
                        .IsUnique();

                    b.HasIndex("DateObservationId");

                    b.HasIndex("HomeId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("ProviderIdentityId", "Version")
                        .IsUnique();

                    b.HasIndex("RawId", "SourceId");

                    b.HasIndex("EventId", "AvailableAtUtc", "RecordedAtUtc");

                    b.ToTable("Results", "football", t =>
                        {
                            t.HasCheckConstraint("CK_Results_Context", "\"HomeId\" <> \"AwayId\" AND length(btrim(\"SourceEventReference\")) > 0 AND length(btrim(\"CompetitionReference\")) > 0 AND length(btrim(\"SeasonReference\")) > 0");

                            t.HasCheckConstraint("CK_Results_Times", "\"AvailableAtUtc\" >= \"RetrievedAtUtc\" AND \"AvailableAtUtc\" <= \"RecordedAtUtc\" AND (\"PublishedAtUtc\" IS NULL OR \"PublishedAtUtc\" <= \"RetrievedAtUtc\")");

                            t.HasCheckConstraint("CK_Results_Version", "\"SchemaVersion\" = 1 AND \"Version\" > 0 AND ((\"Version\" = 1 AND \"CorrectsId\" IS NULL) OR (\"Version\" > 1 AND \"CorrectsId\" IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Governance.PolicyAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousAuditId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PreviousSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reviewer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourcePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("SourcePolicyId", "RecordedAtUtc");

                    b.HasIndex("SourcePolicyId", "Sequence")
                        .IsUnique();

                    b.HasIndex("PreviousAuditId", "SourcePolicyId", "PreviousSequence");

                    b.ToTable("PolicyAudits", "governance", t =>
                        {
                            t.HasCheckConstraint("CK_PolicyAudits_Audit", "length(btrim(\"Reviewer\")) > 0 AND length(btrim(\"Reason\")) > 0");

                            t.HasCheckConstraint("CK_PolicyAudits_Previous", "(\"Sequence\" = 1 AND \"PreviousAuditId\" IS NULL AND \"PreviousSequence\" IS NULL) OR (\"Sequence\" > 1 AND \"PreviousAuditId\" IS NOT NULL AND \"PreviousSequence\" IS NOT NULL AND \"PreviousSequence\" = \"Sequence\" - 1)");

                            t.HasCheckConstraint("CK_PolicyAudits_Status", "(\"Status\" = 'Approved' AND \"ApprovedAtUtc\" IS NOT NULL AND \"ApprovedAtUtc\" >= \"ReviewedAtUtc\") OR (\"Status\" = 'Revoked' AND \"ApprovedAtUtc\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Governance.PurposePermission", b =>
                {
                    b.Property<Guid>("SourcePolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Attribution")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("MaximumRetentionDays")
                        .HasColumnType("integer");

                    b.HasKey("SourcePolicyId", "Purpose");

                    b.ToTable("PurposePermissions", "governance", t =>
                        {
                            t.HasCheckConstraint("CK_PurposePermissions_Decision", "\"Decision\" IN ('Allowed','Denied','Unknown')");

                            t.HasCheckConstraint("CK_PurposePermissions_Purpose", "\"Purpose\" IN ('MetadataDiscovery','DataRetrieval','RawPayloadStorage','HistoricalRetention','InternalAnalytics','PublicDisplay','ModelTraining','CommercialUse','Redistribution')");

                            t.HasCheckConstraint("CK_PurposePermissions_Restrictions", "(\"MaximumRetentionDays\" IS NULL OR \"MaximumRetentionDays\" > 0) AND (\"Attribution\" IS NULL OR length(btrim(\"Attribution\")) > 0)");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Governance.SourcePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EffectiveFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("TermsReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Version")
                        .IsUnique();

                    b.HasIndex("DataSourceId", "EffectiveFromUtc", "EffectiveToUtc");

                    b.ToTable("SourcePolicies", "governance", t =>
                        {
                            t.HasCheckConstraint("CK_SourcePolicies_Evidence", "length(btrim(\"TermsReference\")) > 0 AND length(btrim(\"EvidenceReference\")) > 0");

                            t.HasCheckConstraint("CK_SourcePolicies_Interval", "\"EffectiveToUtc\" IS NULL OR \"EffectiveToUtc\" > \"EffectiveFromUtc\"");

                            t.HasCheckConstraint("CK_SourcePolicies_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Identity.IdentityResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportingEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PreviousDecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousDecisionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PreviousVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalCompetitionId");

                    b.HasIndex("CanonicalParticipantId");

                    b.HasIndex("CanonicalSeasonId");

                    b.HasIndex("CanonicalSportId");

                    b.HasIndex("CanonicalSportingEventId");

                    b.HasIndex("ProviderIdentityId", "Version")
                        .IsUnique();

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("ProviderIdentityId", "DataSourceId", "EntityKind");

                    b.HasIndex("ProviderIdentityId", "DecidedAtUtc", "Version");

                    b.HasIndex("ProviderIdentityId", "RecordedAtUtc", "Version");

                    b.HasIndex("PreviousDecisionId", "ProviderIdentityId", "PreviousVersion", "PreviousDecidedAtUtc");

                    b.ToTable("IdentityResolutions", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_IdentityResolutions_Audit", "length(btrim(\"DecidedBy\")) > 0 AND length(btrim(\"Reason\")) > 0");

                            t.HasCheckConstraint("CK_IdentityResolutions_Previous", "(\"Version\" = 1 AND \"PreviousDecisionId\" IS NULL AND \"PreviousVersion\" IS NULL AND \"PreviousDecidedAtUtc\" IS NULL) OR (\"Version\" > 1 AND \"PreviousDecisionId\" IS NOT NULL AND \"PreviousVersion\" IS NOT NULL AND \"PreviousDecidedAtUtc\" IS NOT NULL AND \"PreviousVersion\" = \"Version\" - 1 AND \"DecidedAtUtc\" >= \"PreviousDecidedAtUtc\")");

                            t.HasCheckConstraint("CK_IdentityResolutions_Target", "(\"Status\" = 'Resolved' AND ((\"EntityKind\" = 'Sport' AND \"CanonicalSportId\" IS NOT NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Competition' AND \"CanonicalCompetitionId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Season' AND \"CanonicalSeasonId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Participant' AND \"CanonicalParticipantId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'SportingEvent' AND \"CanonicalSportingEventId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL))) OR (\"Status\" IN ('Unresolved','Ambiguous') AND (\"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Identity.ProviderIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "EntityKind", "ExternalId")
                        .IsUnique();

                    b.ToTable("ProviderIdentities", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderIdentities_ExternalId", "length(btrim(\"ExternalId\")) > 0");

                            t.HasCheckConstraint("CK_ProviderIdentities_Kind", "\"EntityKind\" IN ('Sport','Competition','Season','Participant','SportingEvent')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Observations.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CanonicalCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportingEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CorrectedAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectedVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrectsObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DateValue")
                        .HasColumnType("date");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SourceEventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusValue")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("TimestampValueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("ProviderIdentityId", "DataSourceId", "EntityKind");

                    b.HasIndex("CanonicalCompetitionId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalParticipantId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSeasonId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSportId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSportingEventId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("EntityKind", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("ProviderIdentityId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CorrectsObservationId", "ProviderIdentityId", "Type", "CorrectedVersion", "CorrectedAvailableAtUtc");

                    b.ToTable("Observations", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_Observations_Availability", "\"AvailableAtUtc\" >= \"RetrievedAtUtc\" AND \"CreatedAtUtc\" >= \"RetrievedAtUtc\"");

                            t.HasCheckConstraint("CK_Observations_Correction", "(\"Version\" = 1 AND \"CorrectsObservationId\" IS NULL AND \"CorrectedVersion\" IS NULL AND \"CorrectedAvailableAtUtc\" IS NULL) OR (\"Version\" > 1 AND \"CorrectsObservationId\" IS NOT NULL AND \"CorrectedVersion\" IS NOT NULL AND \"CorrectedAvailableAtUtc\" IS NOT NULL AND \"CorrectedVersion\" = \"Version\" - 1 AND \"AvailableAtUtc\" >= \"CorrectedAvailableAtUtc\")");

                            t.HasCheckConstraint("CK_Observations_Target", "(\"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Sport' AND \"CanonicalSportId\" IS NOT NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Competition' AND \"CanonicalCompetitionId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Season' AND \"CanonicalSeasonId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Participant' AND \"CanonicalParticipantId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'SportingEvent' AND \"CanonicalSportingEventId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL)");

                            t.HasCheckConstraint("CK_Observations_Value", "(\"DateValue\" IS NULL AND ((\"Type\" = 'DisplayName' AND \"EntityKind\" <> 'SportingEvent' AND \"TextValue\" IS NOT NULL AND length(btrim(\"TextValue\")) > 0 AND \"TimestampValueUtc\" IS NULL AND \"StatusValue\" IS NULL) OR (\"Type\" = 'ScheduledStart' AND \"EntityKind\" = 'SportingEvent' AND \"TextValue\" IS NULL AND \"TimestampValueUtc\" IS NOT NULL AND \"StatusValue\" IS NULL) OR (\"Type\" = 'EventStatus' AND \"EntityKind\" = 'SportingEvent' AND \"TextValue\" IS NULL AND \"TimestampValueUtc\" IS NULL AND \"StatusValue\" IS NOT NULL AND \"StatusValue\" IN ('Scheduled','InProgress','Completed','Postponed','Cancelled')))) OR (\"Type\" = 'EventDate' AND \"EntityKind\" = 'SportingEvent' AND \"DateValue\" IS NOT NULL AND \"TextValue\" IS NULL AND \"TimestampValueUtc\" IS NULL AND \"StatusValue\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Quality.MaintenanceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExecutedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PreviousReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ExecutionId", "Sequence")
                        .IsUnique();

                    b.HasIndex("TargetId", "RecordedAtUtc", "Id");

                    b.ToTable("MaintenanceEvents", "quality", t =>
                        {
                            t.HasCheckConstraint("CK_MaintenanceEvents_Audit", "\"Sequence\" IN (1,2) AND length(btrim(\"OperatorId\")) > 0 AND length(btrim(\"Reason\")) > 0 AND length(btrim(\"Action\")) > 0 AND length(btrim(\"Result\")) > 0");

                            t.HasCheckConstraint("CK_MaintenanceEvents_Time", "\"ExecutedAtUtc\" <= \"RecordedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Quality.QualityAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("BlocksEligibility")
                        .HasColumnType("boolean");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ContextKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ObservationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecordReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RuleVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("RunId", "DataSourceId");

                    b.HasIndex("RunId", "Row");

                    b.HasIndex("ProviderIdentityId", "RecordedAtUtc", "Id");

                    b.HasIndex("ExecutionId", "RawPayloadId", "Row", "RuleId", "RuleVersion")
                        .IsUnique();

                    b.ToTable("QualityAssessments", "quality", t =>
                        {
                            t.HasCheckConstraint("CK_QualityAssessments_Rule", "\"RuleVersion\" > 0 AND \"Row\" >= 0 AND length(btrim(\"RuleId\")) > 0 AND length(btrim(\"ReasonCode\")) > 0");

                            t.HasCheckConstraint("CK_QualityAssessments_Severity", "\"Severity\" IN ('Info','Warning','Error','Critical')");

                            t.HasCheckConstraint("CK_QualityAssessments_Time", "\"AssessedAtUtc\" <= \"RecordedAtUtc\"");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Competitions", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Competitions_Country", "\"CountryCode\" IS NULL OR \"CountryCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_Competitions_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Competitions_Type", "\"CompetitionType\" IN ('League','Tournament','Other')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.EventParticipant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "ParticipantId");

                    b.HasIndex("EventId", "Position")
                        .IsUnique();

                    b.HasIndex("EventId", "SportId");

                    b.HasIndex("ParticipantId", "SportId");

                    b.ToTable("EventParticipants", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_EventParticipants_Side", "(\"Position\" = 1 AND \"Role\" IN ('Home','Side1')) OR (\"Position\" = 2 AND \"Role\" IN ('Away','Side2'))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Participants", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Participants_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Participants_Type", "\"ParticipantType\" IN ('Team','Individual')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Seasons", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Seasons_Dates", "\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_Seasons_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sports", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Sports_Code", "\"Code\" ~ '^[a-z][a-z0-9-]*$'");

                            t.HasCheckConstraint("CK_Sports_Name", "length(btrim(\"DisplayName\")) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "football",
                            DisplayName = "Football"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "tennis",
                            DisplayName = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "basketball",
                            DisplayName = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "ice-hockey",
                            DisplayName = "IceHockey"
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "SportId");

                    b.HasIndex("SeasonId", "CompetitionId");

                    b.HasIndex("SportId", "ScheduledStartUtc");

                    b.ToTable("SportingEvents", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_SportingEvents_Status", "\"Status\" IN ('Scheduled','InProgress','Completed','Postponed','Cancelled')");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DataSources", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_DataSources_Code_NotBlank", "length(btrim(\"Code\")) > 0");

                            t.HasCheckConstraint("CK_DataSources_DisplayName_NotBlank", "length(btrim(\"DisplayName\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DatasetArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BuiltAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DefinitionFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FeatureSchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionFingerprint");

                    b.HasIndex("ManifestHash")
                        .IsUnique();

                    b.ToTable("Snapshots", "datasets", t =>
                        {
                            t.HasCheckConstraint("CK_Snapshots_Content", "\"RowCount\" BETWEEN 1 AND 100 AND \"FeatureSchemaVersion\" IN (1,2) AND octet_length(\"Content\") BETWEEN 1 AND 16777216");

                            t.HasCheckConstraint("CK_Snapshots_Hash", "\"ManifestHash\" ~ '^[0-9a-f]{64}$' AND \"DefinitionFingerprint\" ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DatasetBuildEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefinitionFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionFingerprint");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("AttemptId", "Sequence")
                        .IsUnique();

                    b.ToTable("BuildEvents", "datasets", t =>
                        {
                            t.HasCheckConstraint("CK_BuildEvents_Result", "(\"Status\" = 'Succeeded') = (\"SnapshotId\" IS NOT NULL) AND length(btrim(\"OperatorId\")) > 0 AND length(btrim(\"Reason\")) > 0");

                            t.HasCheckConstraint("CK_BuildEvents_State", "(\"Sequence\" = 1 AND \"Status\" = 'Requested') OR (\"Sequence\" = 2 AND \"Status\" = 'Running') OR (\"Sequence\" = 3 AND \"Status\" IN ('Succeeded','Failed','Cancelled'))");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DatasetFeatureRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("DatasetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("PredictionCutoffUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.HasKey("Id");

                    b.HasIndex("DatasetId", "EventId", "PredictionCutoffUtc")
                        .IsUnique();

                    b.ToTable("Features", "datasets", t =>
                        {
                            t.HasCheckConstraint("CK_Features_Hash", "\"Fingerprint\" ~ '^[0-9a-f]{64}$' AND octet_length(\"Content\") BETWEEN 1 AND 16777216");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.FootballRawContext", b =>
                {
                    b.Property<Guid>("RawId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("SeasonReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("RawId");

                    b.HasIndex("RawId", "SourceId");

                    b.ToTable("FootballRawContexts", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_FootballRawContexts_Scope", "length(btrim(\"CompetitionReference\")) > 0 AND length(btrim(\"SeasonReference\")) > 0 AND \"Version\" = 1");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedRecords")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ApprovalAuditId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<string[]>("Issues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ParsedRecords")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("RejectedRecords")
                        .HasColumnType("integer");

                    b.Property<int>("RetrievedPayloads")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<int>("UnresolvedIdentities")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalAuditId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("AttemptId", "Sequence")
                        .IsUnique();

                    b.HasIndex("RunId", "DataSourceId");

                    b.ToTable("IngestionAuditEvents", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_IngestionAuditEvents_Counts", "\"Sequence\" IN (1,2) AND \"RetrievedPayloads\" >= 0 AND \"ParsedRecords\" >= 0 AND \"AcceptedRecords\" >= 0 AND \"RejectedRecords\" >= 0 AND \"UnresolvedIdentities\" >= 0");

                            t.HasCheckConstraint("CK_IngestionAuditEvents_Outcome", "(\"Sequence\" = 1 AND \"Outcome\" = 'Running') OR (\"Sequence\" = 2 AND \"Outcome\" IN ('Succeeded','Partial','Denied','Failed','Interrupted','Reused'))");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionPublication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedRecords")
                        .HasColumnType("integer");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsBatch")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "Key")
                        .IsUnique();

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("RunId", "DataSourceId");

                    b.ToTable("IngestionPublications", "ingestion");
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "CreatedAtUtc");

                    b.ToTable("IngestionRuns", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_IngestionRuns_Status", "\"Status\" IN ('Pending', 'Running', 'Succeeded', 'Failed')");

                            t.HasCheckConstraint("CK_IngestionRuns_Times", "\"CompletedAtUtc\" IS NULL OR (\"StartedAtUtc\" IS NOT NULL AND \"CompletedAtUtc\" >= \"StartedAtUtc\")");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.RawPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("IngestionRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHashSha256");

                    b.HasIndex("DataSourceId", "RetrievedAtUtc");

                    b.HasIndex("IngestionRunId", "DataSourceId");

                    b.ToTable("RawPayloads", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_RawPayloads_ContentType_NotBlank", "length(btrim(\"ContentType\")) > 0");

                            t.HasCheckConstraint("CK_RawPayloads_Hash", "\"ContentHashSha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_RawPayloads_Length", "\"ByteLength\" IS NULL OR \"ByteLength\" BETWEEN 1 AND 1048576");

                            t.HasCheckConstraint("CK_RawPayloads_StorageKey_NotBlank", "length(btrim(\"StorageKey\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.FootballResultArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("MetadataSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("MetadataSnapshotId");

                    b.ToTable("ResultArtifacts", "datasets", t =>
                        {
                            t.HasCheckConstraint("CK_ResultArtifacts_Hash", "\"Hash\" ~ '^[0-9a-f]{64}$' AND octet_length(\"Content\") <= 16777216 AND \"SchemaVersion\" = 3");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Coverage.CoverageEvidence", b =>
                {
                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawId", "SourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Coverage.CoverageReview", b =>
                {
                    b.HasOne("BetStats.Domain.Coverage.CoverageEvidence", null)
                        .WithMany()
                        .HasForeignKey("EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Coverage.EventTimeEvidence", b =>
                {
                    b.HasOne("BetStats.Domain.Coverage.EventTimeEvidence", null)
                        .WithMany()
                        .HasForeignKey("CorrectsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("DateObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawId", "SourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Football.FootballResultObservation", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("AwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Football.FootballResultObservation", null)
                        .WithMany()
                        .HasForeignKey("CorrectsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("DateObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawId", "SourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Governance.PolicyAudit", b =>
                {
                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany("Audit")
                        .HasForeignKey("SourcePolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Governance.PolicyAudit", null)
                        .WithMany()
                        .HasForeignKey("PreviousAuditId", "SourcePolicyId", "PreviousSequence")
                        .HasPrincipalKey("Id", "SourcePolicyId", "Sequence")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Governance.PurposePermission", b =>
                {
                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany("Permissions")
                        .HasForeignKey("SourcePolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Governance.SourcePolicy", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Identity.IdentityResolution", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CanonicalCompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("CanonicalParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportingEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId", "DataSourceId", "EntityKind")
                        .HasPrincipalKey("Id", "DataSourceId", "EntityKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Identity.IdentityResolution", null)
                        .WithMany()
                        .HasForeignKey("PreviousDecisionId", "ProviderIdentityId", "PreviousVersion", "PreviousDecidedAtUtc")
                        .HasPrincipalKey("Id", "ProviderIdentityId", "Version", "DecidedAtUtc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Identity.ProviderIdentity", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Observations.Observation", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CanonicalCompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("CanonicalParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportingEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId", "DataSourceId", "EntityKind")
                        .HasPrincipalKey("Id", "DataSourceId", "EntityKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("CorrectsObservationId", "ProviderIdentityId", "Type", "CorrectedVersion", "CorrectedAvailableAtUtc")
                        .HasPrincipalKey("Id", "ProviderIdentityId", "Type", "Version", "AvailableAtUtc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Quality.MaintenanceEvent", b =>
                {
                    b.HasOne("BetStats.Domain.Identity.IdentityResolution", null)
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Quality.QualityAssessment", b =>
                {
                    b.HasOne("BetStats.Domain.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Competition", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.EventParticipant", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Participant", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Season", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId", "CompetitionId")
                        .HasPrincipalKey("Id", "CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DatasetBuildEvent", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DatasetArtifact", null)
                        .WithMany()
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DatasetFeatureRecord", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DatasetArtifact", null)
                        .WithMany()
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.FootballRawContext", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawId", "SourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionAuditEvent", b =>
                {
                    b.HasOne("BetStats.Domain.Governance.PolicyAudit", null)
                        .WithMany()
                        .HasForeignKey("ApprovalAuditId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Governance.SourcePolicy", null)
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionPublication", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("RunId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionRun", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.RawPayload", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.FootballResultArtifact", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DatasetArtifact", null)
                        .WithMany()
                        .HasForeignKey("MetadataSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Governance.SourcePolicy", b =>
                {
                    b.Navigation("Audit");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
