// <auto-generated />
using System;
using BetStats.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BetStats.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BetStatsDbContext))]
    [Migration("20261008001440_CanonicalSportsAndTemporalObservations")]
    partial class CanonicalSportsAndTemporalObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ingestion")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BetStats.Domain.Identity.IdentityResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportingEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("PreviousDecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PreviousDecisionId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PreviousVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalCompetitionId");

                    b.HasIndex("CanonicalParticipantId");

                    b.HasIndex("CanonicalSeasonId");

                    b.HasIndex("CanonicalSportId");

                    b.HasIndex("CanonicalSportingEventId");

                    b.HasIndex("ProviderIdentityId", "Version")
                        .IsUnique();

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("ProviderIdentityId", "DataSourceId", "EntityKind");

                    b.HasIndex("ProviderIdentityId", "DecidedAtUtc", "Version");

                    b.HasIndex("PreviousDecisionId", "ProviderIdentityId", "PreviousVersion", "PreviousDecidedAtUtc");

                    b.ToTable("IdentityResolutions", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_IdentityResolutions_Audit", "length(btrim(\"DecidedBy\")) > 0 AND length(btrim(\"Reason\")) > 0");

                            t.HasCheckConstraint("CK_IdentityResolutions_Previous", "(\"Version\" = 1 AND \"PreviousDecisionId\" IS NULL AND \"PreviousVersion\" IS NULL AND \"PreviousDecidedAtUtc\" IS NULL) OR (\"Version\" > 1 AND \"PreviousDecisionId\" IS NOT NULL AND \"PreviousVersion\" IS NOT NULL AND \"PreviousDecidedAtUtc\" IS NOT NULL AND \"PreviousVersion\" = \"Version\" - 1 AND \"DecidedAtUtc\" >= \"PreviousDecidedAtUtc\")");

                            t.HasCheckConstraint("CK_IdentityResolutions_Target", "(\"Status\" = 'Resolved' AND ((\"EntityKind\" = 'Sport' AND \"CanonicalSportId\" IS NOT NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Competition' AND \"CanonicalCompetitionId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Season' AND \"CanonicalSeasonId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Participant' AND \"CanonicalParticipantId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'SportingEvent' AND \"CanonicalSportingEventId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL))) OR (\"Status\" IN ('Unresolved','Ambiguous') AND (\"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Identity.ProviderIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "EntityKind", "ExternalId")
                        .IsUnique();

                    b.ToTable("ProviderIdentities", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_ProviderIdentities_ExternalId", "length(btrim(\"ExternalId\")) > 0");

                            t.HasCheckConstraint("CK_ProviderIdentities_Kind", "\"EntityKind\" IN ('Sport','Competition','Season','Participant','SportingEvent')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Observations.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CanonicalCompetitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CanonicalSportingEventId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CorrectedAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CorrectedVersion")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorrectsObservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("ProviderIdentityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RawPayloadId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SourceEventTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StatusValue")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TextValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("TimestampValueUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RawPayloadId", "DataSourceId");

                    b.HasIndex("ProviderIdentityId", "DataSourceId", "EntityKind");

                    b.HasIndex("CanonicalCompetitionId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalParticipantId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSeasonId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSportId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CanonicalSportingEventId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("EntityKind", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("ProviderIdentityId", "AvailableAtUtc", "CreatedAtUtc", "Id");

                    b.HasIndex("CorrectsObservationId", "ProviderIdentityId", "Type", "CorrectedVersion", "CorrectedAvailableAtUtc");

                    b.ToTable("Observations", "provenance", t =>
                        {
                            t.HasCheckConstraint("CK_Observations_Availability", "\"AvailableAtUtc\" >= \"RetrievedAtUtc\" AND \"CreatedAtUtc\" >= \"RetrievedAtUtc\"");

                            t.HasCheckConstraint("CK_Observations_Correction", "(\"Version\" = 1 AND \"CorrectsObservationId\" IS NULL AND \"CorrectedVersion\" IS NULL AND \"CorrectedAvailableAtUtc\" IS NULL) OR (\"Version\" > 1 AND \"CorrectsObservationId\" IS NOT NULL AND \"CorrectedVersion\" IS NOT NULL AND \"CorrectedAvailableAtUtc\" IS NOT NULL AND \"CorrectedVersion\" = \"Version\" - 1 AND \"AvailableAtUtc\" >= \"CorrectedAvailableAtUtc\")");

                            t.HasCheckConstraint("CK_Observations_Target", "(\"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Sport' AND \"CanonicalSportId\" IS NOT NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Competition' AND \"CanonicalCompetitionId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Season' AND \"CanonicalSeasonId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalParticipantId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'Participant' AND \"CanonicalParticipantId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalSportingEventId\" IS NULL) OR (\"EntityKind\" = 'SportingEvent' AND \"CanonicalSportingEventId\" IS NOT NULL AND \"CanonicalSportId\" IS NULL AND \"CanonicalCompetitionId\" IS NULL AND \"CanonicalSeasonId\" IS NULL AND \"CanonicalParticipantId\" IS NULL)");

                            t.HasCheckConstraint("CK_Observations_Value", "(\"Type\" = 'DisplayName' AND \"EntityKind\" <> 'SportingEvent' AND \"TextValue\" IS NOT NULL AND length(btrim(\"TextValue\")) > 0 AND \"TimestampValueUtc\" IS NULL AND \"StatusValue\" IS NULL) OR (\"Type\" = 'ScheduledStart' AND \"EntityKind\" = 'SportingEvent' AND \"TextValue\" IS NULL AND \"TimestampValueUtc\" IS NOT NULL AND \"StatusValue\" IS NULL) OR (\"Type\" = 'EventStatus' AND \"EntityKind\" = 'SportingEvent' AND \"TextValue\" IS NULL AND \"TimestampValueUtc\" IS NULL AND \"StatusValue\" IS NOT NULL AND \"StatusValue\" IN ('Scheduled','InProgress','Completed','Postponed','Cancelled'))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Competitions", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Competitions_Country", "\"CountryCode\" IS NULL OR \"CountryCode\" ~ '^[A-Z]{2}$'");

                            t.HasCheckConstraint("CK_Competitions_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Competitions_Type", "\"CompetitionType\" IN ('League','Tournament','Other')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.EventParticipant", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "ParticipantId");

                    b.HasIndex("EventId", "Position")
                        .IsUnique();

                    b.HasIndex("EventId", "SportId");

                    b.HasIndex("ParticipantId", "SportId");

                    b.ToTable("EventParticipants", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_EventParticipants_Side", "(\"Position\" = 1 AND \"Role\" IN ('Home','Side1')) OR (\"Position\" = 2 AND \"Role\" IN ('Away','Side2'))");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Participants", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Participants_Name", "length(btrim(\"Name\")) > 0");

                            t.HasCheckConstraint("CK_Participants_Type", "\"ParticipantType\" IN ('Team','Individual')");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Seasons", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Seasons_Dates", "\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_Seasons_Name", "length(btrim(\"Name\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Sport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Sports", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_Sports_Code", "\"Code\" ~ '^[a-z][a-z0-9-]*$'");

                            t.HasCheckConstraint("CK_Sports_Name", "length(btrim(\"DisplayName\")) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "football",
                            DisplayName = "Football"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "tennis",
                            DisplayName = "Tennis"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "basketball",
                            DisplayName = "Basketball"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "ice-hockey",
                            DisplayName = "IceHockey"
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "SportId");

                    b.HasIndex("SeasonId", "CompetitionId");

                    b.HasIndex("SportId", "ScheduledStartUtc");

                    b.ToTable("SportingEvents", "canonical", t =>
                        {
                            t.HasCheckConstraint("CK_SportingEvents_Status", "\"Status\" IN ('Scheduled','InProgress','Completed','Postponed','Cancelled')");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.DataSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DataSources", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_DataSources_Code_NotBlank", "length(btrim(\"Code\")) > 0");

                            t.HasCheckConstraint("CK_DataSources_DisplayName_NotBlank", "length(btrim(\"DisplayName\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId", "CreatedAtUtc");

                    b.ToTable("IngestionRuns", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_IngestionRuns_Status", "\"Status\" IN ('Pending', 'Running', 'Succeeded', 'Failed')");

                            t.HasCheckConstraint("CK_IngestionRuns_Times", "\"CompletedAtUtc\" IS NULL OR (\"StartedAtUtc\" IS NOT NULL AND \"CompletedAtUtc\" >= \"StartedAtUtc\")");
                        });
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.RawPayload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("IngestionRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHashSha256");

                    b.HasIndex("DataSourceId", "RetrievedAtUtc");

                    b.HasIndex("IngestionRunId", "DataSourceId");

                    b.ToTable("RawPayloads", "ingestion", t =>
                        {
                            t.HasCheckConstraint("CK_RawPayloads_ContentType_NotBlank", "length(btrim(\"ContentType\")) > 0");

                            t.HasCheckConstraint("CK_RawPayloads_Hash", "\"ContentHashSha256\" ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("CK_RawPayloads_StorageKey_NotBlank", "length(btrim(\"StorageKey\")) > 0");
                        });
                });

            modelBuilder.Entity("BetStats.Domain.Identity.IdentityResolution", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CanonicalCompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("CanonicalParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportingEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId", "DataSourceId", "EntityKind")
                        .HasPrincipalKey("Id", "DataSourceId", "EntityKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Identity.IdentityResolution", null)
                        .WithMany()
                        .HasForeignKey("PreviousDecisionId", "ProviderIdentityId", "PreviousVersion", "PreviousDecidedAtUtc")
                        .HasPrincipalKey("Id", "ProviderIdentityId", "Version", "DecidedAtUtc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Identity.ProviderIdentity", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Observations.Observation", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CanonicalCompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("CanonicalParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany()
                        .HasForeignKey("CanonicalSportingEventId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.RawPayload", null)
                        .WithMany()
                        .HasForeignKey("RawPayloadId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BetStats.Domain.Identity.ProviderIdentity", null)
                        .WithMany()
                        .HasForeignKey("ProviderIdentityId", "DataSourceId", "EntityKind")
                        .HasPrincipalKey("Id", "DataSourceId", "EntityKind")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Observations.Observation", null)
                        .WithMany()
                        .HasForeignKey("CorrectsObservationId", "ProviderIdentityId", "Type", "CorrectedVersion", "CorrectedAvailableAtUtc")
                        .HasPrincipalKey("Id", "ProviderIdentityId", "Type", "Version", "AvailableAtUtc")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Competition", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.EventParticipant", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.SportingEvent", null)
                        .WithMany("Participants")
                        .HasForeignKey("EventId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Participant", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.Season", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.HasOne("BetStats.Domain.Sports.Sport", null)
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId", "SportId")
                        .HasPrincipalKey("Id", "SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Domain.Sports.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId", "CompetitionId")
                        .HasPrincipalKey("Id", "CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.IngestionRun", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BetStats.Infrastructure.Persistence.Entities.RawPayload", b =>
                {
                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.DataSource", null)
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BetStats.Infrastructure.Persistence.Entities.IngestionRun", null)
                        .WithMany()
                        .HasForeignKey("IngestionRunId", "DataSourceId")
                        .HasPrincipalKey("Id", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("BetStats.Domain.Sports.SportingEvent", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
