<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <ProjectReference Include="../BetStats.Application/BetStats.Application.csproj" />
    <ProjectReference Include="../BetStats.Infrastructure/BetStats.Infrastructure.csproj" />
  </ItemGroup>
</Project>