<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/BetStats.Api/BetStats.Api.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <ProjectReference Include="../../src/BetStats.Infrastructure/BetStats.Infrastructure.csproj" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>
</Project>
